I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00gamemenu.rpy", line 173, in script
    $ ui.interact()
  File "renpy/common/00gamemenu.rpy", line 173, in <module>
    $ ui.interact()
  File "game/encyclopaedia.rpy", line 428, in execute
    screen encyclopaedia_entry:
  File "game/encyclopaedia.rpy", line 428, in execute
    screen encyclopaedia_entry:
  File "game/encyclopaedia.rpy", line 438, in execute
    window:
  File "game/encyclopaedia.rpy", line 445, in execute
    vbox:
  File "game/encyclopaedia.rpy", line 448, in execute
    frame:
  File "game/encyclopaedia.rpy", line 453, in execute
    $page_indicator= "0" + str(encyclopaedia.getEntryData()[0]) + ": " + str(encyclopaedia.getEntryData()[1].name)
  File "game/encyclopaedia.rpy", line 453, in <module>
    $page_indicator= "0" + str(encyclopaedia.getEntryData()[0]) + ": " + str(encyclopaedia.getEntryData()[1].name)
AttributeError: 'int' object has no attribute 'name'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00gamemenu.rpy", line 173, in script
    $ ui.interact()
  File "E:\_RenPy\renpy-6.99.11-sdk\renpy\ast.py", line 805, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "E:\_RenPy\renpy-6.99.11-sdk\renpy\python.py", line 1641, in py_exec_bytecode
    exec bytecode in globals, locals
  File "renpy/common/00gamemenu.rpy", line 173, in <module>
    $ ui.interact()
  File "E:\_RenPy\renpy-6.99.11-sdk\renpy\ui.py", line 278, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "E:\_RenPy\renpy-6.99.11-sdk\renpy\display\core.py", line 2496, in interact
    repeat, rv = self.interact_core(preloads=preloads, **kwargs)
  File "E:\_RenPy\renpy-6.99.11-sdk\renpy\display\core.py", line 2764, in interact_core
    root_widget.visit_all(lambda i : i.per_interact())
  File "E:\_RenPy\renpy-6.99.11-sdk\renpy\display\core.py", line 464, in visit_all
    d.visit_all(callback)
  File "E:\_RenPy\renpy-6.99.11-sdk\renpy\display\core.py", line 464, in visit_all
    d.visit_all(callback)
  File "E:\_RenPy\renpy-6.99.11-sdk\renpy\display\core.py", line 464, in visit_all
    d.visit_all(callback)
  File "E:\_RenPy\renpy-6.99.11-sdk\renpy\display\screen.py", line 394, in visit_all
    callback(self)
  File "E:\_RenPy\renpy-6.99.11-sdk\renpy\display\core.py", line 2764, in <lambda>
    root_widget.visit_all(lambda i : i.per_interact())
  File "E:\_RenPy\renpy-6.99.11-sdk\renpy\display\screen.py", line 404, in per_interact
    self.update()
  File "E:\_RenPy\renpy-6.99.11-sdk\renpy\display\screen.py", line 573, in update
    self.screen.function(**self.scope)
  File "game/encyclopaedia.rpy", line 428, in execute
    screen encyclopaedia_entry:
  File "game/encyclopaedia.rpy", line 428, in execute
    screen encyclopaedia_entry:
  File "game/encyclopaedia.rpy", line 438, in execute
    window:
  File "game/encyclopaedia.rpy", line 445, in execute
    vbox:
  File "game/encyclopaedia.rpy", line 448, in execute
    frame:
  File "game/encyclopaedia.rpy", line 453, in execute
    $page_indicator= "0" + str(encyclopaedia.getEntryData()[0]) + ": " + str(encyclopaedia.getEntryData()[1].name)
  File "game/encyclopaedia.rpy", line 453, in <module>
    $page_indicator= "0" + str(encyclopaedia.getEntryData()[0]) + ": " + str(encyclopaedia.getEntryData()[1].name)
AttributeError: 'int' object has no attribute 'name'

Windows-8-6.2.9200
Ren'Py 6.99.11.1749
Apothecary Game 0.1
