I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/encyclopaedia_data.rpy", line 7, in script
    init python:
  File "game/encyclopaedia_data.rpy", line 1654, in <module>
    locking_unlocking_entries,
NameError: name 'locking_unlocking_entries' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/encyclopaedia_data.rpy", line 7, in script
    init python:
  File "E:\_RenPy\renpy-6.99.12.2-sdk\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "E:\_RenPy\renpy-6.99.12.2-sdk\renpy\python.py", line 1695, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/encyclopaedia_data.rpy", line 1654, in <module>
    locking_unlocking_entries,
NameError: name 'locking_unlocking_entries' is not defined

Windows-8-6.2.9200
Ren'Py 6.99.12.2.2029
Apothecary Game 0.1
