I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 225, in script
    $ calendar.getpast(300)
  File "game/script.rpy", line 225, in <module>
    $ calendar.getpast(300)
  File "game/calendar.rpy", line 246, in getpast
    self.past_date = self.past_days_count[self._pastmonth]
TypeError: 'int' object has no attribute '__getitem__'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 225, in script
    $ calendar.getpast(300)
  File "E:\_RenPy\renpy-6.99.12.2-sdk\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "E:\_RenPy\renpy-6.99.12.2-sdk\renpy\python.py", line 1695, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script.rpy", line 225, in <module>
    $ calendar.getpast(300)
  File "game/calendar.rpy", line 246, in getpast
    self.past_date = self.past_days_count[self._pastmonth]
TypeError: 'int' object has no attribute '__getitem__'

Windows-8-6.2.9200
Ren'Py 6.99.12.2.2029
Apothecary Game 0.1
