I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 246, in script
    $ calendar.between_dates(cnt1=daycount_from_gamestart, cnt2=calendar.past_daycount)
  File "game/script.rpy", line 246, in <module>
    $ calendar.between_dates(cnt1=daycount_from_gamestart, cnt2=calendar.past_daycount)
NameError: name 'daycount_from_gamestart' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 246, in script
    $ calendar.between_dates(cnt1=daycount_from_gamestart, cnt2=calendar.past_daycount)
  File "E:\_RenPy\renpy-6.99.12.2-sdk\renpy\ast.py", line 814, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "E:\_RenPy\renpy-6.99.12.2-sdk\renpy\python.py", line 1695, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script.rpy", line 246, in <module>
    $ calendar.between_dates(cnt1=daycount_from_gamestart, cnt2=calendar.past_daycount)
NameError: name 'daycount_from_gamestart' is not defined

Windows-8-6.2.9200
Ren'Py 6.99.12.2.2029
Apothecary Game 0.1
